export const courses = [
  {"id": "scenario-sales-excel", "icon": "01", "category": "office", "nodes": ["chat", "tools"], "zh": {"title": "把三张销售表整理成经营报表", "outcome": "统一字段与口径，留下公式、图表和异常清单。", "audience": "Excel 报表", "result": "经营报表 + 异常清单"}, "en": {"title": "Turn three sales sheets into a report", "outcome": "Reconcile fields and totals, with formulas, charts and an exception log.", "audience": "Excel reports", "result": "Editable workbook + exception log"}},
  {"id": "scenario-business-ppt", "icon": "02", "category": "office", "nodes": ["chat", "tools"], "zh": {"title": "把业务资料做成汇报 PPT", "outcome": "先确认结构，再生成可编辑图表与讲稿。", "audience": "汇报演示", "result": "8 页 PPT + PDF + 讲稿"}, "en": {"title": "Turn business data into a presentation", "outcome": "Agree on the outline, then create editable charts and speaker notes.", "audience": "Presentations", "result": "8-slide deck + PDF + speaker notes"}},
  {"id": "scenario-client-proposal", "icon": "03", "category": "office", "nodes": ["chat", "tools"], "zh": {"title": "把零散材料整理成客户方案", "outcome": "范围、费用和验收有依据，未决事项留待确认。", "audience": "客户方案", "result": "Word 方案 + PDF"}, "en": {"title": "Create a client proposal from source material", "outcome": "Define scope, pricing and acceptance, with open questions clearly marked.", "audience": "Client proposals", "result": "Word proposal + PDF"}},
  {"id": "scenario-supplier-quotes", "icon": "04", "category": "office", "nodes": ["chat", "tools"], "zh": {"title": "比较三份供应商报价", "outcome": "统一含税含运费价格，一起检查交期与保修。", "audience": "采购比价", "result": "报价对比表 + 追问清单"}, "en": {"title": "Compare three supplier quotes", "outcome": "Compare landed costs, delivery times and warranty requirements.", "audience": "Procurement", "result": "Comparison workbook + follow-up questions"}},
  {"id": "scenario-feedback-analysis", "icon": "05", "category": "office", "nodes": ["chat", "tools"], "zh": {"title": "从用户反馈中找到改进重点", "outcome": "保留原文和编号，让分类、统计和建议可追溯。", "audience": "反馈分析", "result": "分类工作簿 + 改进建议"}, "en": {"title": "Find improvement priorities in feedback", "outcome": "Keep source text and IDs linked to categories, counts and recommendations.", "audience": "Feedback analysis", "result": "Classification workbook + recommendations"}},
  {"id": "scenario-client-brief", "icon": "06", "category": "office", "nodes": ["chat", "tools"], "zh": {"title": "准备客户拜访资料包", "outcome": "一页简报、八个问题，为三十分钟沟通做好准备。", "audience": "客户拜访", "result": "客户简报 + 问题与邮件草稿"}, "en": {"title": "Prepare for a client meeting", "outcome": "Bring a one-page brief and eight questions to a 30-minute conversation.", "audience": "Client meetings", "result": "Client brief + questions + email draft"}},
  {"id": "scenario-campaign-review", "icon": "07", "category": "office", "nodes": ["chat", "tools"], "zh": {"title": "把活动数据整理成复盘报告", "outcome": "核对转化口径，用证据支持下一轮行动。", "audience": "活动复盘", "result": "分析表 + Word 复盘"}, "en": {"title": "Turn campaign data into a review", "outcome": "Check conversion definitions and support next steps with evidence.", "audience": "Campaign reviews", "result": "Analysis workbook + Word review"}},
  {"id": "scenario-monthly-refresh", "icon": "08", "category": "office", "nodes": ["chat", "tools"], "zh": {"title": "换一批数据更新月度报表", "outcome": "沿用统计口径，保留历史，另存新版本。", "audience": "月度更新", "result": "新版报表 + 更新说明"}, "en": {"title": "Refresh a monthly report with new data", "outcome": "Reuse definitions, preserve history and save a new version.", "audience": "Monthly reporting", "result": "Updated workbook + change notes"}},

  { id: "scenario-project-handoff", icon: "09", category: "everyday", nodes: ["projects", "notes"], zh: { title: "接手陌生项目，找到下一步", outcome: "从三份交接资料，整理目标、风险和行动清单。", audience: "项目交接", result: "项目概览 + 交接笔记" }, en: { title: "Take over an unfamiliar project", outcome: "Turn three handoff documents into goals, risks and next actions.", audience: "Project handoff", result: "Project overview + handoff note" } },
  { id: "scenario-weekly-report", icon: "10", category: "everyday", nodes: ["chat", "notes", "tasks"], zh: { title: "把零散工作整理成周报", outcome: "核对工作日志与任务状态，写出有依据的周报。", audience: "日常办公", result: "周报 + 下周计划" }, en: { title: "Turn work logs into a weekly report", outcome: "Check facts and task status before writing a clear weekly update.", audience: "Everyday work", result: "Weekly report + next-week plan" } },
  { id: "scenario-meeting-actions", icon: "11", category: "everyday", nodes: ["voice", "notes"], zh: { title: "把会议录音变成行动清单", outcome: "从音频转写到人工核对，保留负责人、依赖和待确认日期。", audience: "会议整理", result: "会议纪要 + 行动清单" }, en: { title: "Turn meeting audio into action items", outcome: "Transcribe, review and retain owners, dependencies and open dates.", audience: "Meeting follow-up", result: "Meeting note + action list" } },
  { id: "scenario-launch-copy", icon: "12", category: "everyday", nodes: ["chat", "notes"], zh: { title: "从需求说明完成发布文案", outcome: "明确受众与事实边界，经过修订形成可审阅的成稿。", audience: "内容创作", result: "发布文案 + 事实核对" }, en: { title: "Write launch copy from a brief", outcome: "Define the audience, review claims and revise a publishable draft.", audience: "Content creation", result: "Launch copy + fact check" } },
  { id: "scenario-daily-tool", icon: "13", category: "everyday", nodes: ["coding", "local-apps"], zh: { title: "做一个每天能用的小工具", outcome: "把具体需求变成专注清单，逐项验证交互与保存。", audience: "个人工具", result: "可用小应用 + 验收记录" }, en: { title: "Build a tool for your daily routine", outcome: "Create a focus checklist and verify interactions and persistence.", audience: "Personal tools", result: "Working app + acceptance checks" } },
  { id: "scenario-competitor-research", icon: "14", category: "everyday", nodes: ["browser", "notes"], zh: { title: "收集资料并完成竞品对比", outcome: "根据官方来源做对比，区分已确认信息与试用问题。", audience: "资料研究", result: "来源对照表 + 选型建议" }, en: { title: "Research and compare two products", outcome: "Use official sources, mark unknowns and make a conditional recommendation.", audience: "Research", result: "Sourced comparison + recommendation" } },
] as const;
