export const storyCopy = {
  zh: {
    eyebrow: "为一个人，也为你的每一个想法。", headline: ["一个人，", "也能让想法走得更远。"],
    description: "记住来时的路，接住未完成的事。xopc 是与你一起把工作向前推进的个人 AI。",
    download: "下载 xopc", begin: "从一个故事开始", hello: "没关系，我们接着来。",
    deskLabel: "未完成的项目、想法和待办围绕着小环", notes: ["那个一直想发布的项目", "灵感 · 昨晚 23:41", "如果，这次真的做出来呢？", "发布之前…", "整理用户反馈", "决定第一版的范围"], stalled: "上次打开，12 天前", loopiHint: "点点小环，和它打个招呼。", closingLine: "今晚，不必做完所有事。又向前一点，就很好。",
    introLabel: "你也有这样一个项目吗？", intro: ["不是不想做。", "只是每次回来，都像重新开始。"],
    introDesc: "散在聊天里的决定，忘在文件里的灵感，还有那个迟迟没有划掉的待办。我们从一个小小的发布计划，接着来。",
    chapterLabel: "从用户反馈到首版发布计划", demoLabel: "情境演示 · 非真实执行", project: "记事应用 · 首版发布", steps: ["接回上下文", "确认范围", "得到发布计划", "手机接着看"],
    chapters: [
      { time: "周一 · 09:08", title: "不用再讲一遍，\n我们走到哪了。", body: "一句“继续上次的项目”，把散落的背景接起来。", aside: "记住上下文，是为了让你轻一点。" },
      { time: "周一 · 09:12", title: "把复杂留给它，\n把决定留给你。", body: "先理清卡住的地方。需要你决定时，xopc 会停下来。", aside: "不是每件事，都需要你亲力亲为。" },
      { time: "周一 · 09:30", title: "少一些来回，\n多一个真正的进展。", body: "示例中，方向确定了。资料、任务和下一步，开始有了着落。", aside: "每一步有结果，也有迹可循。" },
      { time: "周一 · 18:06", title: "换个地方，\n不必换个开头。", body: "离开桌面，在手机上继续。同一个项目，同一段上下文。", aside: "连接电脑上的 xopc，接着聊。" },
    ],
    ask: "继续记事应用的发布准备。我们卡在哪里？", context: "接回首版发布的线索", sources: ["用户反馈", "发布清单", "范围讨论"], fact: "从资料中找到", factBody: "用户希望更快记录、找回笔记。发布清单还在等待首版范围。", inference: "建议下一步", inferenceBody: "先做好记录与搜索，把多人协作留到之后。",
    decision: "第一版，先做好记录与搜索？", decisionBody: "保留：快速记录、全文搜索。\n暂缓：多人协作、共享空间。", confirm: "试一下：确认这个范围", confirmed: "已确认 · 查看结果", reset: "重新体验", approved: "由你决定", approvalNote: "这里只演示确认流程，不会操作你的项目。",
    result: "首版发布计划已更新", exampleResult: "示例中，确认后得到的结果", tasks: ["用户反馈整理为 3 个重点", "首版范围：快速记录 + 全文搜索", "发布清单：补充搜索验收任务"], ready: "可查看", file: "首版发布计划", fileBody: "范围已明确 · 下一步可执行", artifactBefore: "等待确认范围", artifactAfter: "范围确认 → 清单更新", artifactPhone: "同一份计划 · 手机可查看",
    phoneTime: "18:06", phoneAsk: "记事应用，接下来先做什么？", phoneReply: "首版保留记录和搜索。发布清单已补充搜索验收任务，下次从这里继续。", connected: "连接电脑上的 xopc", continuity: "同一个项目，同一份结果。", continue: "查看发布计划", recap: "上下文接起来，下一步就清楚了。",
    filmLength: "完整产品演示 · 3 分 35 秒", filmTitle: "看看真正的 xopc，\n如何接住手头的事。", filmDesc: "从带入资料到检查结果。完整演示保留每一步，让你看清它如何工作。", moreFilms: "查看实战教程",
    trustLabel: "帮你推进，也让你掌控。", trustTitle: "事情在向前。\n决定仍在你手里。", trust: [
      { title: "资料放在哪里，说清楚", body: "核心状态本地保存。使用云模型时，请求上下文由对应提供商处理。" },
      { title: "重要操作，先确认", body: "发送、删除和其他高影响操作，先停下来，等你决定。" },
      { title: "记住什么，你可以修改", body: "查看、纠正或删除它记住的内容。你的上下文，由你掌握。" },
    ], privacy: "查看隐私与数据边界",
    downloadKicker: "从你在意的下一件事开始。", downloadTitle: "把 xopc 带到你的桌面。", downloadDesc: "安装后连接模型服务，再带入你希望它参考的资料。", mobileDownload: "在手机上继续",
  },
  en: {
    eyebrow: "For you. And everything you want to make.", headline: ["On your own.", "Further, together."],
    description: "A little less to carry. A little more momentum. Meet the personal AI that remembers where you left off and helps you move forward.",
    download: "Download xopc", begin: "Follow the story", hello: "It's okay. Let's pick it back up.",
    deskLabel: "Unfinished projects, ideas and to-dos surrounding Loopi", notes: ["That project I keep coming back to", "A THOUGHT · 11:41 PM", "What if I actually made it?", "BEFORE THE LAUNCH…", "Read the user feedback", "Decide what belongs in v1"], stalled: "Last opened 12 days ago", loopiHint: "Give Loopi a little tap. Say hello.", closingLine: "Not everything needs finishing tonight. A little further is enough.",
    introLabel: "SOUND FAMILIAR?", intro: ["The idea is still there.", "So why does it feel like starting over?"], introDesc: "Decisions buried in chats. Ideas tucked into files. That one task you never quite get to. Let's pick up a little launch plan together.",
    chapterLabel: "From user feedback to a launch plan", demoLabel: "Illustrative scenario · no real actions", project: "Notes app · first release", steps: ["Find the context", "Choose the scope", "Get a launch plan", "Take it with you"],
    chapters: [
      { time: "09:08 · CONTEXT", title: "Pick up the thread.\nSkip the recap.", body: "Feedback, checklists and earlier decisions come back into one project.", aside: "The material you bring in becomes the starting point." },
      { time: "09:12 · YOUR DECISION", title: "See the trade-off.\nChoose the next step.", body: "Keep quick capture and search in v1. Save collaboration for later.", aside: "Try confirming the scope to see what changes." },
      { time: "09:30 · THE RESULT", title: "More than a reply.\nA plan you can use.", body: "In this example, confirming the scope leads to summarized feedback and an updated checklist.", aside: "See exactly what changed." },
      { time: "18:06 · ON YOUR PHONE", title: "Leave your desk.\nKeep your context.", body: "Review the same launch plan on your phone, without explaining it all again.", aside: "Connect to xopc running on your computer." },
    ],
    ask: "Let's continue the notes app launch. What's blocking us?", context: "Picking up the launch context", sources: ["User feedback", "Launch checklist", "Scope discussion"], fact: "FROM YOUR MATERIAL", factBody: "Users want faster capture and easier search. The launch checklist is waiting for a scope decision.", inference: "A SUGGESTED NEXT STEP", inferenceBody: "Focus on capture and search. Save collaboration for later.",
    decision: "Focus v1 on capture and search?", decisionBody: "Keep: quick capture, full-text search.\nLater: collaboration, shared spaces.", confirm: "Try it: confirm this scope", confirmed: "Confirmed · see the result", reset: "Try again", approved: "Your decision", approvalNote: "This demonstrates approval. It won't change your projects.",
    result: "Launch plan updated", exampleResult: "Example result after approval", tasks: ["Feedback distilled into 3 priorities", "V1 scope: quick capture + full-text search", "Search acceptance task added to checklist"], ready: "Ready to review", file: "Version one · launch plan", fileBody: "A clear scope. An actionable next step.", artifactBefore: "Scope awaiting approval", artifactAfter: "Scope agreed → checklist updated", artifactPhone: "Same plan · available on your phone",
    phoneTime: "18:06", phoneAsk: "What's next for the notes app?", phoneReply: "V1 keeps capture and search. The checklist now includes search acceptance testing. We can pick up there next time.", connected: "Connected to xopc on your computer", continuity: "Same project. Same result.", continue: "View the launch plan", recap: "Connect the context. Find the next step.",
    filmLength: "FULL WALKTHROUGH · 3:39", filmTitle: "The real workspace.\nThe work behind the story.", filmDesc: "From bringing in material to checking results. Watch the full workflow, with each step in view.", moreFilms: "Explore guided tutorials",
    trustLabel: "HELP THAT KEEPS YOU IN CONTROL", trustTitle: "Work moves forward.\nThe direction stays yours.", trust: [
      { title: "Know where your data goes", body: "Core state stays local. When you use cloud models, their providers process the request context." },
      { title: "Important actions need approval", body: "Sending, deleting and other high-impact actions pause for your confirmation." },
      { title: "Memory you can change", body: "See, correct or delete what it remembers. Your context stays in your control." },
    ], privacy: "Explore privacy and data boundaries",
    downloadKicker: "Start with the next thing you care about.", downloadTitle: "Make room for xopc.", downloadDesc: "Install, connect a model provider, and bring in the material you want it to use.", mobileDownload: "Continue on mobile",
  },
};
