import type { Locale } from "@/lib/i18n/config";

type LocalizedText = Record<Locale, string>;

export type UseCaseCategory = "start" | "organize" | "research" | "create" | "build" | "automate";

export type UseCase = {
  id: string;
  category: UseCaseCategory;
  title: LocalizedText;
  summary: LocalizedText;
  prompt: LocalizedText;
  outcome: LocalizedText;
  setup: LocalizedText[];
  approval: LocalizedText;
  evidence: LocalizedText[];
  productNodes: string[];
};

const t = (zh: string, en: string): LocalizedText => ({ zh, en });

export const useCaseCategories: Array<{ id: UseCaseCategory; label: LocalizedText; description: LocalizedText }> = [
  { id: "start", label: t("从这里开始", "Start here"), description: t("把模糊想法变成可继续推进的工作。", "Turn an incomplete thought into work that can keep moving.") },
  { id: "organize", label: t("整理事务", "Organize"), description: t("从邮件、日程和本地材料中找出真正要做的事。", "Find the real work hidden in email, calendars, and local material.") },
  { id: "research", label: t("研究与比较", "Research"), description: t("查找来源、比较选项，留下可核验的结论。", "Find sources, compare options, and leave a verifiable conclusion.") },
  { id: "create", label: t("创作与交付", "Create"), description: t("从已有材料生成可以继续使用的内容与文件。", "Turn source material into content and files you can keep using.") },
  { id: "build", label: t("开发与构建", "Build"), description: t("在本地项目中编码、验证并交付结果。", "Code, verify, and deliver inside local projects.") },
  { id: "automate", label: t("持续运行", "Keep it moving"), description: t("把做过一次的工作变成定时或持续检查。", "Turn one completed task into scheduled or continuing work.") },
];

export const useCases: UseCase[] = [
  {
    id: "shape-a-task",
    category: "start",
    title: t("把脑中的一团事理成下一步", "Turn a messy thought into a next step"),
    summary: t("不必先写完整需求。把背景、顾虑和零散想法告诉 xopc，让它整理目标、边界和可执行的下一步。", "You do not need a polished brief. Give xopc the context, concerns, and fragments; it can shape the objective, boundaries, and next action."),
    prompt: t("我脑子里有一件还没想清楚的事：[描述现状]。先帮我区分事实、假设和待决定的问题，再整理成一个明确目标、完成标准和最小下一步。信息不足时一次问完。", "I have something I have not fully worked through: [describe the situation]. Separate facts, assumptions, and decisions, then turn it into a clear objective, completion criteria, and the smallest next step. Ask for missing information in one round."),
    outcome: t("一份明确的任务约定和下一步，不只是聊天总结。", "A clear task contract and next action, not just a chat summary."),
    setup: [],
    approval: t("只整理和建议，不会替你作关键决定。", "It organizes and recommends without making key decisions for you."),
    evidence: [t("目标与完成标准", "Objective and completion criteria"), t("下一步与阻塞项", "Next action and blockers")],
    productNodes: ["chat", "tasks", "home"],
  },
  {
    id: "resume-project",
    category: "start",
    title: t("接着上次的项目继续做", "Pick up a project where you left off"),
    summary: t("让 xopc 汇总项目中的任务、对话、笔记与最近结果，指出当前最值得推进的工作。", "Let xopc bring together tasks, conversations, notes, and recent results, then identify the most useful work to move next."),
    prompt: t("打开项目 [项目名]。根据已有任务、笔记和最近结果，告诉我现在处于什么状态、有哪些未决问题，以及今天最值得完成的一件事。确认后继续推进。", "Open project [project name]. Using its tasks, notes, and recent results, tell me where things stand, what remains unresolved, and the single most useful thing to finish today. Continue after I confirm."),
    outcome: t("跨会话保留的项目状态和明确的继续入口。", "Durable project state and a clear place to resume across sessions."),
    setup: [],
    approval: t("在改变项目方向前由你确认。", "You confirm before the project direction changes."),
    evidence: [t("项目状态摘要", "Project status summary"), t("最近结果与下一步", "Recent results and next action")],
    productNodes: ["projects", "memory", "tasks"],
  },
  {
    id: "voice-capture",
    category: "start",
    title: t("把一段语音变成可执行计划", "Turn a voice note into an actionable plan"),
    summary: t("口述想法或会议复盘，让 xopc 转写、提取决定与行动项，并放进任务或笔记。", "Speak an idea or meeting recap, then let xopc transcribe it, extract decisions and actions, and place them in tasks or notes."),
    prompt: t("转写这段语音，区分决定、行动项、问题和背景。把有明确负责人与截止时间的内容整理成任务，其余内容保存为笔记；先给我预览。", "Transcribe this recording and separate decisions, actions, questions, and context. Turn items with clear owners and deadlines into tasks, save the rest as a note, and show me a preview first."),
    outcome: t("从语音直接得到结构化笔记和待办事项。", "Structured notes and actionable work directly from speech."),
    setup: [t("配置语音识别模型", "Configure a speech-to-text model")],
    approval: t("创建或改动任务前先预览。", "Preview before tasks are created or changed."),
    evidence: [t("完整转写", "Full transcript"), t("行动项清单", "Action list")],
    productNodes: ["voice", "capture", "notes", "tasks"],
  },
  {
    id: "inbox-promises",
    category: "organize",
    title: t("找出邮件里答应过却没完成的事", "Find promises in your inbox that slipped"),
    summary: t("在你授权的 Gmail 范围内查找承诺、截止时间和未回复事项，并准备下一步。", "Search the Gmail scope you authorize for commitments, deadlines, and unanswered threads, then prepare the next step."),
    prompt: t("检查最近 [30] 天的邮件，找出我明确答应过但还没有完成或回复的事情。按影响和时效排序，为每一项写出证据、建议动作和回复草稿。不要发送。", "Review the last [30] days of email for things I explicitly promised but have not completed or answered. Rank them by impact and urgency, and provide evidence, a suggested action, and a reply draft for each. Do not send anything."),
    outcome: t("一份有邮件证据、可直接处理的承诺清单。", "An actionable commitment list backed by email evidence."),
    setup: [t("连接 Gmail", "Connect Gmail")],
    approval: t("发送邮件始终需要你的明确确认。", "Sending email always requires your explicit confirmation."),
    evidence: [t("来源邮件", "Source messages"), t("待发送草稿", "Draft replies")],
    productNodes: ["connectors", "tasks", "permissions"],
  },
  {
    id: "daily-plan",
    category: "organize",
    title: t("从日历和任务生成今日计划", "Build today's plan from calendar and tasks"),
    summary: t("合并已有会议、任务和时间边界，给出一份实际可执行的日程，而不是无限待办。", "Combine meetings, tasks, and time boundaries into a realistic day rather than an endless list."),
    prompt: t("查看我今天的日历和未完成任务。保留固定安排，按精力与截止时间安排最多三件重要工作，并标出缓冲时间和可能冲突。先给计划，不要改日历。", "Review today's calendar and open tasks. Keep fixed commitments, schedule no more than three important pieces of work around energy and deadlines, and flag buffers and conflicts. Show the plan without changing my calendar."),
    outcome: t("带冲突提示和优先级的现实日程。", "A realistic schedule with priorities and conflict warnings."),
    setup: [t("连接 Google Calendar", "Connect Google Calendar")],
    approval: t("写入或移动日历事件前确认。", "Confirm before creating or moving calendar events."),
    evidence: [t("引用的日历事件", "Referenced calendar events"), t("计划与冲突说明", "Plan and conflict notes")],
    productNodes: ["connectors", "home", "tasks"],
  },
  {
    id: "organize-files",
    category: "organize",
    title: t("整理一个混乱的本地文件夹", "Organize a messy local folder"),
    summary: t("读取指定工作区内的文件，识别重复、过期和未归档内容，先提出规则再执行。", "Inspect files inside an authorized workspace, identify duplicates and unfiled material, and propose rules before applying them."),
    prompt: t("分析文件夹 [路径]，按内容和日期提出一个简单的整理结构。列出重复文件、无法判断的文件和拟执行的移动/重命名操作。先给预览，我确认后再修改，并保留变更记录。", "Analyze folder [path] and propose a simple structure based on content and date. List duplicates, ambiguous files, and every proposed move or rename. Preview first, apply only after I confirm, and keep a change log."),
    outcome: t("可回顾的整理方案、变更记录和更清晰的文件结构。", "A reviewable organization plan, change log, and clearer folder structure."),
    setup: [t("授权指定工作区", "Authorize the intended workspace")],
    approval: t("移动、重命名或删除前确认。", "Confirm before moving, renaming, or deleting files."),
    evidence: [t("操作前预览", "Pre-change preview"), t("文件变更清单", "File change log")],
    productNodes: ["tools", "permissions", "notes"],
  },
  {
    id: "receipt-ledger",
    category: "organize",
    title: t("把收据整理成费用台账", "Turn receipts into an expense ledger"),
    summary: t("从图片或 PDF 提取商户、日期、金额和类别，标出无法确认的数据，并生成表格。", "Extract merchant, date, amount, and category from images or PDFs, flag uncertain fields, and produce a spreadsheet."),
    prompt: t("读取这些收据文件。提取日期、商户、金额、币种、税额和费用类别，保留原文件链接。对低置信度字段做标记，生成汇总表和异常清单，不要猜测缺失数字。", "Read these receipt files. Extract date, merchant, amount, currency, tax, and category while keeping links to the source files. Flag low-confidence fields, produce a summary table and an exceptions list, and do not invent missing numbers."),
    outcome: t("一份能核对来源的费用表和异常清单。", "A source-linked expense table and an exceptions list."),
    setup: [t("启用文件与表格能力", "Enable file and spreadsheet capabilities")],
    approval: t("只生成文件，不会自动报销或付款。", "It creates files without submitting reimbursements or payments."),
    evidence: [t("来源文件链接", "Source file links"), t("低置信度字段", "Low-confidence fields")],
    productNodes: ["media", "skills", "tools"],
  },
  {
    id: "compare-options",
    category: "research",
    title: t("带着约束比较产品或服务", "Compare products or services against your constraints"),
    summary: t("把预算、硬性条件和偏好交给 xopc，让它查找当前信息并解释取舍。", "Give xopc your budget, hard constraints, and preferences so it can find current information and explain the trade-offs."),
    prompt: t("帮我比较 [产品/服务]。预算是 [预算]，必须满足 [硬性条件]，偏好是 [偏好]。只使用当前可访问的可靠来源，给出候选、总成本、主要取舍和推荐，并附来源和查询日期。不要购买。", "Compare [product/service] for me. My budget is [budget], hard requirements are [requirements], and preferences are [preferences]. Use reliable current sources, show candidates, total cost, trade-offs, and a recommendation with source links and lookup dates. Do not purchase."),
    outcome: t("有来源、有约束、有取舍说明的推荐。", "A sourced recommendation grounded in constraints and trade-offs."),
    setup: [t("启用网页搜索", "Enable web search")],
    approval: t("购买或提交订单前必须由你确认。", "You must confirm before any purchase or order is submitted."),
    evidence: [t("来源链接与日期", "Source links and dates"), t("比较表", "Comparison table")],
    productNodes: ["tools", "browser", "permissions"],
  },
  {
    id: "source-brief",
    category: "research",
    title: t("做一份可追溯的研究简报", "Create a traceable research brief"),
    summary: t("围绕一个问题收集公开资料，区分事实、观点和未知，并把结论保存成笔记。", "Gather public material around a question, separate facts from opinions and unknowns, and save the conclusion as a note."),
    prompt: t("研究 [问题]，优先使用一手和权威来源。把确定事实、不同观点、仍未知的部分分开写，所有关键结论都附来源和发布日期。最后给我一页摘要，并保存为项目笔记。", "Research [question], prioritizing primary and authoritative sources. Separate established facts, competing views, and remaining unknowns; cite every important conclusion with its publication date. Finish with a one-page summary and save it as a project note."),
    outcome: t("一份能回到原始来源核验的简报。", "A brief whose conclusions can be checked against original sources."),
    setup: [t("启用网页搜索", "Enable web search")],
    approval: t("保存到项目前可先预览。", "Preview before saving it to a project."),
    evidence: [t("逐条来源", "Claim-level sources"), t("研究日期", "Research date")],
    productNodes: ["tools", "notes", "projects"],
  },
  {
    id: "account-admin",
    category: "research",
    title: t("在网站里完成一项账户事务", "Handle an account task in the browser"),
    summary: t("让 xopc 在已连接的浏览器中查找设置、准备表单或客服信息，并在真正提交前停下。", "Let xopc use a connected browser to find settings, prepare forms, or gather support information, then stop before the real submission."),
    prompt: t("在 [网站] 中处理 [账户事务]。先确认当前状态和可行路径，填写或准备所需内容，但在发送消息、取消服务、修改账户或付款前停下来让我确认。完成后给出页面状态和确认信息。", "Handle [account task] on [website]. First verify the current state and available path, prepare the required content, but pause before sending messages, canceling services, changing the account, or paying. When complete, report the final page state and confirmation information."),
    outcome: t("浏览器中的真实进展，同时保留最后决定权。", "Real browser progress while keeping the final decision with you."),
    setup: [t("连接浏览器并授权站点", "Connect a browser and authorize the site")],
    approval: t("外部写入、取消、购买和账户变更前确认。", "Confirm before external writes, cancellations, purchases, or account changes."),
    evidence: [t("操作前后状态", "Before-and-after state"), t("确认号或截图", "Confirmation number or screenshot")],
    productNodes: ["browser", "chrome", "permissions"],
  },
  {
    id: "draft-from-files",
    category: "create",
    title: t("从一组材料写出可交付初稿", "Draft a deliverable from source files"),
    summary: t("把本地文档、笔记和要求组合成结构化初稿，并明确哪些内容来自哪里。", "Combine local documents, notes, and requirements into a structured draft with clear source provenance."),
    prompt: t("根据这些材料起草一份 [报告/方案/说明]。先列出你将使用的来源和结构，再生成初稿。不要补造材料里没有的数字或结论；不确定的地方用待确认标记，并给出交付文件。", "Draft a [report/proposal/guide] from these materials. First list the sources and proposed structure, then create the draft. Do not invent numbers or conclusions not present in the source material; mark uncertainties for review and provide the deliverable file."),
    outcome: t("有来源边界、可继续编辑的交付文件。", "An editable deliverable with clear source boundaries."),
    setup: [t("授权源文件所在工作区", "Authorize the workspace containing the source files")],
    approval: t("发布或发送文件前确认。", "Confirm before publishing or sending the file."),
    evidence: [t("使用的来源清单", "Source list"), t("生成的文件", "Generated file")],
    productNodes: ["skills", "tools", "notes"],
  },
  {
    id: "image-variants",
    category: "create",
    title: t("生成并迭代一组视觉方案", "Generate and iterate on visual directions"),
    summary: t("描述用途、比例和视觉边界，先获得少量方向，再基于具体反馈继续修改。", "Describe the purpose, aspect ratio, and visual boundaries, get a small set of directions, then iterate with concrete feedback."),
    prompt: t("为 [用途] 生成视觉方案。目标受众是 [受众]，比例是 [比例]，必须包含 [元素]，避免 [元素/风格]。先提出三个清晰方向，选定后再生成并根据我的具体反馈迭代。", "Create visual directions for [purpose]. The audience is [audience], aspect ratio is [ratio], required elements are [elements], and avoid [elements/styles]. Propose three distinct directions first, then generate and iterate after I choose one."),
    outcome: t("经过方向确认和反馈迭代的图像文件。", "Image files refined through direction selection and feedback."),
    setup: [t("配置图像生成模型", "Configure an image generation model")],
    approval: t("每轮方向由你选择，不自动发布。", "You choose each direction; nothing is published automatically."),
    evidence: [t("生成文件", "Generated files"), t("采用的提示与修改记录", "Prompt and revision history")],
    productNodes: ["media", "skills", "projects"],
  },
  {
    id: "publish-local-app",
    category: "create",
    title: t("把一个想法做成本地小工具", "Turn an idea into a local tool"),
    summary: t("从目标和输入输出开始，让 xopc 构建一个在本机运行、可继续迭代的小应用。", "Start with the objective and inputs/outputs, then let xopc build a local app that can run on your machine and keep evolving."),
    prompt: t("为 [用户/场景] 做一个本地小工具，解决 [问题]。输入是 [输入]，需要输出 [输出]。先给最小版本和验收标准，再实现、运行检查并给我使用入口。未经确认不要部署到公网。", "Build a local tool for [user/scenario] that solves [problem]. Its input is [input] and output is [output]. Define the smallest version and acceptance criteria, implement it, verify it runs, and give me the local entry point. Do not deploy it publicly without confirmation."),
    outcome: t("一个能在本机打开并验证的应用，而不只是代码片段。", "A locally runnable, verified app rather than a code snippet."),
    setup: [t("启用编码与本地运行能力", "Enable coding and local runtime capabilities")],
    approval: t("公网发布、购买域名或外部部署前确认。", "Confirm before public deployment, domain purchases, or external hosting."),
    evidence: [t("运行结果", "Runtime result"), t("验收标准检查", "Acceptance checks")],
    productNodes: ["local-apps", "coding", "runtimes"],
  },
  {
    id: "implement-change",
    category: "build",
    title: t("在真实代码库中实现并验证改动", "Implement and verify a change in a real codebase"),
    summary: t("让 xopc 阅读本地仓库规则、定位相关代码、实施最小改动并运行验证。", "Let xopc read repository rules, locate the relevant code, implement the smallest change, and run verification."),
    prompt: t("在仓库 [路径] 实现：[需求]。先读取仓库说明和现有模式，说明会影响哪些区域，然后做最小改动。运行相关测试、类型检查或构建；保留用户已有改动，并报告文件、验证结果和剩余风险。", "In repository [path], implement: [requirement]. Read repository guidance and existing patterns first, explain the affected areas, then make the smallest change. Run relevant tests, type checks, or builds; preserve existing user changes and report files, verification, and remaining risks."),
    outcome: t("与仓库约定一致、经过验证的代码改动。", "A verified code change that follows the repository's conventions."),
    setup: [t("授权代码工作区与命令执行", "Authorize the code workspace and command execution")],
    approval: t("高风险命令、发布和外部写入前确认。", "Confirm before risky commands, releases, or external writes."),
    evidence: [t("代码差异", "Code diff"), t("测试或构建结果", "Test or build result")],
    productNodes: ["coding", "tools", "projects"],
  },
  {
    id: "review-change",
    category: "build",
    title: t("审查一次代码改动并指出真正风险", "Review a code change for real risks"),
    summary: t("结合仓库上下文检查正确性、回归、安全和测试缺口，避免只做表面风格评论。", "Use repository context to check correctness, regressions, security, and test gaps rather than offering surface-level style comments."),
    prompt: t("审查 [分支/PR/改动]。优先查找会导致错误结果、数据损坏、安全问题或兼容性回归的问题。每个发现给出文件位置、触发条件和修复建议；没有实质问题就明确说明。不要修改代码。", "Review [branch/PR/change]. Prioritize issues that can cause incorrect results, data loss, security problems, or compatibility regressions. For each finding, give the file location, trigger condition, and fix; say clearly if there are no material issues. Do not modify code."),
    outcome: t("按风险排序、可定位和复现的审查结论。", "Risk-ranked findings that are locatable and reproducible."),
    setup: [t("授权本地仓库，或连接 GitHub", "Authorize a local repository or connect GitHub")],
    approval: t("默认只读，不会评论、合并或推送。", "Read-only by default; it will not comment, merge, or push."),
    evidence: [t("精确文件位置", "Exact file locations"), t("验证方式", "Verification method")],
    productNodes: ["coding", "connectors", "permissions"],
  },
  {
    id: "morning-brief",
    category: "automate",
    title: t("每天生成一份带来源的行业简报", "Create a sourced industry brief every day"),
    summary: t("先手动跑通一次研究任务，再把同一套来源、范围和输出格式保存为自动化。", "Run the research task successfully once, then save the same sources, scope, and output format as an automation."),
    prompt: t("每天 [时间] 检查 [主题和来源范围]。只报告自上次运行以来的重要变化，附来源、发布时间和为什么值得关注。没有实质变化时保持安静；失败时通知我并保留可恢复状态。", "Every day at [time], check [topic and source scope]. Report only meaningful changes since the last run, including sources, publication time, and why each matters. Stay quiet when nothing material changed; notify me on failure and preserve a resumable state."),
    outcome: t("低噪音、可核验、失败可见的持续简报。", "A low-noise, verifiable brief with visible failures."),
    setup: [t("启用网页搜索与 Automation", "Enable web search and Automations")],
    approval: t("自动读取和生成结果；外部发送按渠道策略确认。", "Reading and result generation can run automatically; external sends follow channel policy."),
    evidence: [t("本次来源与变化", "Sources and changes for this run"), t("运行回执", "Run receipt")],
    productNodes: ["automations", "tools", "tasks"],
  },
  {
    id: "deadline-heartbeat",
    category: "automate",
    title: t("只在真正需要时提醒我", "Remind me only when attention is actually needed"),
    summary: t("让 Heartbeat 周期性查看任务或日程，但在状态没有实质变化时保持安静。", "Let Heartbeat periodically check tasks or calendar state while staying quiet when nothing meaningful has changed."),
    prompt: t("定期检查 [项目/任务范围]。只有在截止时间临近、任务阻塞、外部状态变化或确实需要我决定时提醒我。提醒中包含原因、证据和最小下一步；无变化时不要发状态消息。", "Periodically check [project/task scope]. Notify me only when a deadline is near, work is blocked, external state changes, or a real decision is needed. Include the reason, evidence, and smallest next step; send no status message when nothing changed."),
    outcome: t("安静但可靠的主动提醒，而不是周期性噪音。", "Quiet but reliable proactive attention instead of periodic noise."),
    setup: [t("配置 Heartbeat 范围和活跃时间", "Configure Heartbeat scope and active hours")],
    approval: t("提醒不会自动扩大已有执行权限。", "A reminder never expands existing execution authority."),
    evidence: [t("触发原因", "Trigger reason"), t("当前状态与下一步", "Current state and next step")],
    productNodes: ["heartbeat", "assistant", "home"],
  },
  {
    id: "repeat-browser-task",
    category: "automate",
    title: t("把跑通的网页操作保存为自动化", "Save a proven browser task as an automation"),
    summary: t("先在你的实际环境中完成并验证一次，再保存可复用步骤；网站变化时停止并报告。", "Complete and verify the task once in your environment, then save the reusable behavior; stop and report when the website changes."),
    prompt: t("把刚刚成功完成的 [网页任务] 保存为可复用自动化。沿用相同站点范围和审批点；每次运行核对关键页面状态，网站结构或结果不符合预期时停止，不要猜着点击，并报告已完成和剩余步骤。", "Save the [browser task] we just completed successfully as a reusable automation. Keep the same site scope and approval points; verify critical page state on every run, stop rather than guessing when the site or result differs, and report completed and remaining steps."),
    outcome: t("基于真实成功记录、能够检测漂移的网页自动化。", "Browser automation based on a real successful run with drift detection."),
    setup: [t("连接浏览器并先成功执行一次", "Connect a browser and complete one successful run first")],
    approval: t("沿用原任务的付款、发送和账户变更审批点。", "Keep the original approval points for payment, sending, and account changes."),
    evidence: [t("步骤完成计数", "Completed step count"), t("最终页面状态", "Final page state")],
    productNodes: ["browser-auto", "browser", "automations"],
  },
  {
    id: "continue-on-phone",
    category: "automate",
    title: t("离开电脑后继续同一件事", "Continue the same work away from your desk"),
    summary: t("通过移动端或消息渠道回到同一个 Runtime，继续查看任务、做决定和接收结果。", "Return to the same Runtime from mobile or a messaging channel to review tasks, make decisions, and receive results."),
    prompt: t("继续处理任务 [任务名]。先给我当前状态、刚完成的结果和现在需要我决定的唯一事项；不要重复已经完成的工作。", "Continue task [task name]. First show the current state, the latest completed result, and the single decision needed from me now; do not repeat work that is already complete."),
    outcome: t("跨设备延续同一任务，而不是开启一段失去上下文的新聊天。", "The same task continues across devices instead of becoming a new contextless chat."),
    setup: [t("连接移动端或消息渠道", "Connect the mobile app or a messaging channel")],
    approval: t("远程入口仍遵守原有权限与确认规则。", "Remote access keeps the original permission and confirmation rules."),
    evidence: [t("任务当前状态", "Current task state"), t("最近执行回执", "Latest execution receipt")],
    productNodes: ["mobile", "channels", "tasks"],
  },
  {
    id: "weekly-review",
    category: "start",
    title: t("用一周的真实结果做下周取舍", "Plan next week from this week's real results"),
    summary: t("汇总已完成、卡住和延期的工作，用执行回执而不是印象决定下周重点。", "Summarize completed, blocked, and delayed work, then choose next week's focus from execution receipts rather than memory."),
    prompt: t("回顾本周的项目、任务和执行结果。区分已完成、仍在进行、被阻塞和已经不重要的事项；指出反复出现的阻塞，并建议下周最多三个重点。先给我取舍建议，不要直接改任务。", "Review this week's projects, tasks, and execution results. Separate completed, active, blocked, and no-longer-important work; identify recurring blockers and recommend at most three priorities for next week. Show the trade-offs before changing tasks."),
    outcome: t("基于实际进展的周回顾和下周重点。", "A weekly review and next-week focus grounded in actual progress."),
    setup: [],
    approval: t("调整、关闭或新建任务前确认。", "Confirm before changing, closing, or creating tasks."),
    evidence: [t("本周完成记录", "This week's completion receipts"), t("重点与取舍依据", "Priority rationale and trade-offs")],
    productNodes: ["home", "projects", "tasks"],
  },
  {
    id: "decision-log",
    category: "start",
    title: t("把一次困难决定留成可回看的记录", "Turn a difficult choice into a durable decision record"),
    summary: t("整理选项、约束、假设和反对理由，做决定后把依据与复盘条件保存下来。", "Structure options, constraints, assumptions, and objections, then preserve the rationale and review conditions after you decide."),
    prompt: t("我需要决定：[问题]。帮我整理选项、硬约束、可逆性、主要风险和仍缺的信息。不要替我决定；在我选择后，把决定、依据、反对意见和何时重新评估保存为项目笔记。", "I need to decide: [question]. Structure the options, hard constraints, reversibility, key risks, and missing information. Do not decide for me; after I choose, save the decision, rationale, objections, and review trigger as a project note."),
    outcome: t("一份能解释当时为什么这样选的决策记录。", "A decision record that explains why the choice made sense at the time."),
    setup: [],
    approval: t("关键选择始终由你作出。", "The key choice always remains yours."),
    evidence: [t("选项与约束", "Options and constraints"), t("决定与复盘条件", "Decision and review trigger")],
    productNodes: ["understanding", "notes", "projects"],
  },
  {
    id: "meeting-followup",
    category: "organize",
    title: t("把会议材料变成决定和跟进", "Turn meeting material into decisions and follow-ups"),
    summary: t("从转写或笔记中提取决定、负责人、截止时间和待确认问题，并准备跟进文本。", "Extract decisions, owners, deadlines, and open questions from a transcript or notes, then prepare the follow-up."),
    prompt: t("根据这份会议转写或笔记，提取已作决定、行动项、负责人、截止时间和待确认问题。标出没有明确负责人的事项，生成任务预览和一封简洁跟进邮件，但不要发送。", "From this meeting transcript or note, extract decisions, actions, owners, deadlines, and open questions. Flag items without an owner, prepare a task preview and a concise follow-up email, but do not send it."),
    outcome: t("结构化会议记录、任务预览和待发送跟进稿。", "Structured meeting notes, a task preview, and a ready-to-review follow-up."),
    setup: [t("提供会议笔记，语音材料需配置转写", "Provide meeting notes; audio requires speech-to-text")],
    approval: t("创建任务和发送跟进前确认。", "Confirm before creating tasks or sending follow-ups."),
    evidence: [t("原文对应位置", "Source references"), t("行动项与负责人", "Actions and owners")],
    productNodes: ["voice", "notes", "tasks"],
  },
  {
    id: "drive-inventory",
    category: "organize",
    title: t("盘点一个共享资料夹", "Inventory a shared folder"),
    summary: t("读取你授权的云端目录，找出重复、陈旧、无主或命名混乱的文件，先给整理建议。", "Inspect an authorized cloud folder for duplicate, stale, unowned, or poorly named files and propose a cleanup first."),
    prompt: t("盘点 Google Drive 文件夹 [名称/链接]。按类型、更新时间和可能归属整理清单，指出重复、陈旧和无法判断的文件，提出最小整理方案。只读分析，不要移动或删除。", "Inventory Google Drive folder [name/link]. Organize the list by type, recency, and likely ownership; flag duplicates, stale files, and ambiguous items, then propose the smallest cleanup plan. Read only—do not move or delete anything."),
    outcome: t("带来源链接的资料盘点和整理建议。", "A source-linked inventory and cleanup recommendation."),
    setup: [t("连接 Google Drive 并授权目标目录", "Connect Google Drive and authorize the target folder")],
    approval: t("移动、重命名、共享或删除前确认。", "Confirm before moving, renaming, sharing, or deleting."),
    evidence: [t("文件清单与链接", "File inventory and links"), t("异常与建议", "Exceptions and recommendations")],
    productNodes: ["connectors", "tools", "permissions"],
  },
  {
    id: "document-inbox",
    category: "organize",
    title: t("把一批散落文档变成项目索引", "Turn a pile of documents into a project index"),
    summary: t("读取授权文件夹中的材料，按主题与时间建立索引，保留出处并标记无法归类的内容。", "Read an authorized folder, index material by theme and date, preserve provenance, and flag what cannot be classified."),
    prompt: t("处理文件夹 [路径] 中的文档。为每份材料提取标题、日期、主题、关键结论和原文件位置，生成项目索引；把重复或无法归类的项目放进异常区，不要修改原文件。", "Process the documents in [path]. Extract title, date, theme, key conclusions, and original location for each, then create a project index. Put duplicates and unclassified items in an exceptions section without modifying source files."),
    outcome: t("可搜索、可追溯的项目资料索引。", "A searchable, traceable index of project material."),
    setup: [t("授权目标工作区", "Authorize the target workspace")],
    approval: t("默认只读，改动源文件前确认。", "Read-only by default; confirm before changing source files."),
    evidence: [t("原文件路径", "Original file paths"), t("索引与异常清单", "Index and exceptions")],
    productNodes: ["tools", "projects", "notes"],
  },
  {
    id: "calendar-conflicts",
    category: "organize",
    title: t("提前发现日历冲突和赶场风险", "Catch calendar conflicts and travel risk early"),
    summary: t("检查重叠会议、缺少缓冲和跨地点安排，给出最小调整方案而不直接改动。", "Detect overlapping events, missing buffers, and location changes, then suggest the smallest adjustment without editing anything."),
    prompt: t("检查未来 [7] 天的日历，找出重叠、连续无缓冲、跨地点时间不足和准备时间缺失的安排。按影响排序并建议最小调整方案；不要移动或取消事件。", "Review the next [7] days of my calendar for overlaps, back-to-back events without buffers, insufficient travel time, and missing preparation time. Rank by impact and suggest the smallest adjustment; do not move or cancel events."),
    outcome: t("一份按风险排序的冲突清单和调整建议。", "A risk-ranked conflict list with adjustment suggestions."),
    setup: [t("连接 Google Calendar", "Connect Google Calendar")],
    approval: t("移动、创建或取消事件前确认。", "Confirm before moving, creating, or canceling events."),
    evidence: [t("相关日历事件", "Relevant calendar events"), t("冲突原因", "Conflict rationale")],
    productNodes: ["connectors", "tasks", "permissions"],
  },
  {
    id: "trip-research",
    category: "research",
    title: t("研究一趟符合约束的旅行", "Research a trip around real constraints"),
    summary: t("根据日期、预算、同行人和节奏查找交通与住宿，明确价格时点与取舍，不代替你预订。", "Research transport and stays around dates, budget, party, and pace, with price timestamps and clear trade-offs—without booking."),
    prompt: t("研究从 [出发地] 到 [目的地]、日期为 [日期] 的旅行。预算和硬性条件是 [约束]。比较交通、住宿和每日节奏，标出价格查询时间、取消条件和主要取舍，给出推荐行程；不要预订。", "Research a trip from [origin] to [destination] on [dates]. Budget and hard constraints are [constraints]. Compare transport, stays, and daily pace; show price lookup times, cancellation terms, and trade-offs, then recommend an itinerary. Do not book."),
    outcome: t("带价格时点、来源和取舍的候选行程。", "A candidate itinerary with price timestamps, sources, and trade-offs."),
    setup: [t("启用网页搜索", "Enable web search")],
    approval: t("预订、付款或提交旅客信息前确认。", "Confirm before booking, payment, or submitting traveler details."),
    evidence: [t("来源和查询时间", "Sources and lookup times"), t("费用与取消条件", "Costs and cancellation terms")],
    productNodes: ["tools", "browser", "projects"],
  },
  {
    id: "policy-change-monitor",
    category: "research",
    title: t("监测官方政策页面的实质变化", "Monitor official policy pages for material changes"),
    summary: t("定期比较指定官方来源，只在条款、日期或要求真正变化时提醒你。", "Periodically compare specified official sources and alert only when terms, dates, or requirements materially change."),
    prompt: t("监测这些官方页面：[链接]。每次运行与上次记录比较，只在资格、截止日期、费用或办理要求发生实质变化时提醒我。附新旧差异、页面时间和来源；页面不可访问时报告失败，不要猜测。", "Monitor these official pages: [links]. Compare each run with the previous record and alert me only when eligibility, deadlines, fees, or process requirements materially change. Include the before/after difference, page date, and source; report access failures rather than guessing."),
    outcome: t("低噪音、可追溯的政策变化提醒。", "Low-noise, traceable policy-change alerts."),
    setup: [t("启用网页访问与 Automation", "Enable web access and Automations")],
    approval: t("只监测和提醒，不会替你提交申请。", "Monitoring and alerts only; it will not submit applications."),
    evidence: [t("新旧差异", "Before/after diff"), t("官方来源与时间", "Official source and timestamp")],
    productNodes: ["automations", "tools", "tasks"],
  },
  {
    id: "reading-digest",
    category: "research",
    title: t("把一批链接和 PDF 读成主题脉络", "Turn links and PDFs into a thematic digest"),
    summary: t("跨多份材料提取共识、分歧和开放问题，同时保留每个结论的出处。", "Extract consensus, disagreements, and open questions across multiple sources while preserving provenance."),
    prompt: t("阅读这些链接和 PDF：[材料]。按主题整理核心观点，区分多方共识、相互冲突和仍未回答的问题。每项结论标注具体来源，最后生成一页摘要和后续阅读建议。", "Read these links and PDFs: [material]. Organize the key ideas by theme and separate consensus, disagreement, and unanswered questions. Cite a specific source for each conclusion, then produce a one-page digest and a suggested reading path."),
    outcome: t("带逐项来源的主题摘要和阅读路径。", "A thematic digest and reading path with claim-level sources."),
    setup: [t("提供可访问的链接或文件", "Provide accessible links or files")],
    approval: t("保存或分享摘要前可先预览。", "Preview before saving or sharing the digest."),
    evidence: [t("逐项来源", "Claim-level sources"), t("共识与分歧表", "Consensus and disagreement map")],
    productNodes: ["tools", "notes", "projects"],
  },
  {
    id: "claim-check",
    category: "research",
    title: t("核验一组说法是否站得住", "Check whether a set of claims holds up"),
    summary: t("把陈述拆成可验证命题，优先查一手来源，并明确支持、反驳和证据不足。", "Break statements into testable claims, prioritize primary sources, and distinguish support, contradiction, and insufficient evidence."),
    prompt: t("核验这些说法：[内容]。先拆成独立命题，优先查找一手和权威来源。对每项给出支持、反驳、证据不足或已过时的判断，附来源日期和限制；不要把推断写成事实。", "Verify these claims: [content]. Split them into independent propositions and prioritize primary and authoritative sources. Mark each as supported, contradicted, insufficiently evidenced, or outdated, with source dates and limitations; do not present inference as fact."),
    outcome: t("逐条可核查、带证据强弱说明的结论。", "Claim-by-claim conclusions with source strength and limitations."),
    setup: [t("启用网页搜索", "Enable web search")],
    approval: t("默认只研究，不会公开发布结论。", "Research only by default; findings are not published."),
    evidence: [t("原始来源", "Primary sources"), t("证据等级与限制", "Evidence strength and limits")],
    productNodes: ["tools", "notes", "understanding"],
  },
  {
    id: "presentation-deck",
    category: "create",
    title: t("从资料做出一份可讲的演示稿", "Build a presentation you can actually deliver"),
    summary: t("先确定受众、叙事和每页目的，再从已有材料生成可继续编辑的演示文件。", "Define the audience, narrative, and purpose of each slide before generating an editable deck from source material."),
    prompt: t("根据这些材料制作一份面向 [受众] 的 [时长] 演示。先给叙事结构和每页目的，我确认后生成演示文件。关键数字注明来源，不确定内容标记待确认，并附讲者备注。", "Create a [duration] presentation for [audience] from these materials. First propose the narrative and purpose of each slide; after I confirm, generate the deck. Cite important numbers, flag uncertainties, and include speaker notes."),
    outcome: t("结构清楚、有来源、可继续编辑的演示文件。", "A clear, sourced, editable presentation file."),
    setup: [t("启用演示文稿能力并提供源材料", "Enable presentation capability and provide source material")],
    approval: t("生成前确认结构，发布或发送前再确认。", "Confirm the structure before generation and again before publishing or sending."),
    evidence: [t("演示文件", "Presentation file"), t("引用来源与待确认项", "Sources and review flags")],
    productNodes: ["skills", "tools", "projects"],
  },
  {
    id: "spreadsheet-cleanup",
    category: "create",
    title: t("清洗一份混乱表格并保留异常", "Clean a messy spreadsheet without hiding exceptions"),
    summary: t("统一日期、金额、分类和重复记录，保留原始数据并输出无法确定的异常项。", "Normalize dates, amounts, categories, and duplicates while preserving raw data and surfacing unresolved exceptions."),
    prompt: t("清洗表格 [文件]。保留原始工作表，统一日期、金额和类别格式，识别重复与缺失值；先说明规则，再生成清洗后的工作表和异常工作表。无法确定的数据不要猜。", "Clean spreadsheet [file]. Preserve the raw sheet, normalize date, amount, and category formats, and identify duplicates and missing values. Explain the rules first, then generate cleaned and exceptions sheets. Do not guess uncertain values."),
    outcome: t("可追溯的清洗表、规则说明和异常清单。", "A traceable cleaned sheet, rule summary, and exceptions list."),
    setup: [t("启用表格能力", "Enable spreadsheet capability")],
    approval: t("不覆盖原文件，替换前确认。", "The original is preserved; confirm before replacing anything."),
    evidence: [t("原始与清洗工作表", "Raw and cleaned sheets"), t("规则与异常", "Rules and exceptions")],
    productNodes: ["skills", "tools", "permissions"],
  },
  {
    id: "pdf-brief",
    category: "create",
    title: t("把定稿内容排成一份正式 PDF", "Turn approved content into a polished PDF"),
    summary: t("基于已确认内容生成排版一致的 PDF，并检查分页、图表和字体渲染。", "Generate a consistently formatted PDF from approved content and verify pagination, charts, and font rendering."),
    prompt: t("把已确认的内容 [材料] 制作成一份 [用途] PDF。保持原意，不新增未经确认的事实；使用清晰层级、目录和页码，生成后逐页检查溢出、断页、字体和图表，并给我最终文件与检查结果。", "Turn the approved material [content] into a PDF for [purpose]. Preserve meaning and add no unapproved facts; use clear hierarchy, a table of contents, and page numbers. After generation, inspect every page for overflow, breaks, fonts, and charts, then provide the file and verification result."),
    outcome: t("经过逐页检查、可直接交付的 PDF。", "A delivery-ready PDF verified page by page."),
    setup: [t("启用文档与 PDF 能力", "Enable document and PDF capabilities")],
    approval: t("内容变更和外部发送前确认。", "Confirm content changes and external sending."),
    evidence: [t("最终 PDF 文件", "Final PDF file"), t("逐页检查结果", "Page-by-page verification")],
    productNodes: ["skills", "tools", "media"],
  },
  {
    id: "share-note",
    category: "create",
    title: t("把一份笔记整理后分享出去", "Polish and share a selected note"),
    summary: t("先审阅分享范围和敏感内容，再生成对外版本，并在真正发布前停下来。", "Review scope and sensitive content, prepare an external version, and pause before the note is actually shared."),
    prompt: t("把笔记 [名称] 整理成适合分享给 [对象] 的版本。保留关键上下文，移除或标记敏感内容，先给最终预览和分享范围；我确认后再发布，并返回分享链接。", "Prepare note [name] for sharing with [audience]. Keep essential context, remove or flag sensitive material, and show the final preview and access scope. Publish only after I confirm, then return the share link."),
    outcome: t("经过范围检查的对外版本和可验证分享链接。", "A scope-reviewed external version and a verifiable share link."),
    setup: [],
    approval: t("发布和权限范围必须明确确认。", "Publishing and access scope require explicit confirmation."),
    evidence: [t("最终预览", "Final preview"), t("分享链接与权限", "Share link and access scope")],
    productNodes: ["sharing", "notes", "permissions"],
  },
  {
    id: "fix-build",
    category: "build",
    title: t("定位并修复一次构建失败", "Diagnose and fix a failing build"),
    summary: t("复现错误、找到首个根因、做最小修复并重新验证，避免顺手改动无关代码。", "Reproduce the failure, find the first root cause, apply the smallest fix, and re-run verification without touching unrelated code."),
    prompt: t("在仓库 [路径] 复现构建失败。先读取项目说明并记录原始错误，定位首个可操作根因，做最小修复后重新运行相关构建和测试。保留现有用户改动，不升级无关依赖，并报告差异和剩余风险。", "Reproduce the build failure in [path]. Read project guidance and capture the original error, identify the first actionable root cause, apply the smallest fix, then rerun the relevant build and tests. Preserve user changes, avoid unrelated upgrades, and report the diff and remaining risk."),
    outcome: t("可解释、经过复验的最小构建修复。", "A minimal, explained build fix that has been re-verified."),
    setup: [t("授权代码仓库与命令执行", "Authorize the repository and command execution")],
    approval: t("破坏性命令、依赖大版本升级和发布前确认。", "Confirm before destructive commands, major dependency upgrades, or release."),
    evidence: [t("修复前后错误", "Before/after build output"), t("代码差异与测试", "Diff and test results")],
    productNodes: ["coding", "tools", "runtimes"],
  },
  {
    id: "release-checklist",
    category: "build",
    title: t("生成一次可核对的发布清单", "Prepare a verifiable release checklist"),
    summary: t("从代码差异、测试和项目约定生成发布说明、风险与回滚检查项，但不自行发布。", "Derive release notes, risks, and rollback checks from the diff, tests, and repository conventions without releasing anything."),
    prompt: t("为 [版本/改动范围] 准备发布清单。根据代码差异和仓库流程列出用户可见变化、迁移项、验证步骤、监控点和回滚条件，生成发布说明草稿。不要打标签、推送或部署。", "Prepare a release checklist for [version/change scope]. From the code diff and repository process, list user-visible changes, migrations, verification steps, monitoring, and rollback conditions, and draft release notes. Do not tag, push, or deploy."),
    outcome: t("有证据支撑的发布清单和说明草稿。", "An evidence-backed release checklist and draft notes."),
    setup: [t("授权代码仓库", "Authorize the code repository")],
    approval: t("提交、打标签、推送和部署前确认。", "Confirm before commit, tag, push, or deploy."),
    evidence: [t("差异与测试依据", "Diff and test evidence"), t("发布与回滚清单", "Release and rollback checklist")],
    productNodes: ["coding", "projects", "tasks"],
  },
  {
    id: "github-watch",
    category: "automate",
    title: t("只在 GitHub 工作真正需要你时提醒", "Watch GitHub and surface only actionable changes"),
    summary: t("持续查看指定 Issue、PR 或 CI 状态，只在失败、阻塞或需要决定时通知。", "Track selected issues, pull requests, or CI status and notify only on failures, blockers, or decisions."),
    prompt: t("监测 GitHub 上的 [仓库/Issue/PR]。只有在 CI 失败、审查出现阻塞、合并条件满足或明确需要我决定时提醒我。附状态变化、相关链接和最小下一步；无实质变化时保持安静，不要评论或合并。", "Monitor [repository/issue/PR] on GitHub. Notify me only when CI fails, review is blocked, merge conditions are met, or a real decision is needed. Include the state change, relevant links, and smallest next step; stay quiet otherwise and do not comment or merge."),
    outcome: t("低噪音、带链接和下一步的开发提醒。", "Low-noise development alerts with links and a clear next step."),
    setup: [t("连接 GitHub 并启用 Automation", "Connect GitHub and enable Automations")],
    approval: t("评论、关闭、合并和推送前确认。", "Confirm before commenting, closing, merging, or pushing."),
    evidence: [t("状态变化与链接", "State change and links"), t("自动化运行回执", "Automation run receipt")],
    productNodes: ["connectors", "automations", "tasks"],
  },
];

export function localized(value: LocalizedText, locale: Locale): string {
  return value[locale];
}
