import type { Locale } from "@/lib/i18n/config";

type LocalizedText = Record<Locale, string>;

export type UseCaseCategory = "start" | "organize" | "research" | "create" | "build" | "automate";

export type UseCase = {
  id: string;
  category: UseCaseCategory;
  title: LocalizedText;
  summary: LocalizedText;
  prompt: LocalizedText;
  outcome: LocalizedText;
  setup: LocalizedText[];
  approval: LocalizedText;
  evidence: LocalizedText[];
  productNodes: string[];
};

const t = (zh: string, en: string): LocalizedText => ({ zh, en });

export const useCaseCategories: Array<{ id: UseCaseCategory; label: LocalizedText; description: LocalizedText }> = [
  { id: "start", label: t("从这里开始", "Start here"), description: t("把模糊想法变成可继续推进的工作。", "Turn an incomplete thought into work that can keep moving.") },
  { id: "organize", label: t("整理事务", "Organize"), description: t("从邮件、日程和本地材料中找出真正要做的事。", "Find the real work hidden in email, calendars, and local material.") },
  { id: "research", label: t("研究与比较", "Research"), description: t("查找来源、比较选项，留下可核验的结论。", "Find sources, compare options, and leave a verifiable conclusion.") },
  { id: "create", label: t("创作与交付", "Create"), description: t("从已有材料生成可以继续使用的内容与文件。", "Turn source material into content and files you can keep using.") },
  { id: "build", label: t("开发与构建", "Build"), description: t("在本地项目中编码、验证并交付结果。", "Code, verify, and deliver inside local projects.") },
  { id: "automate", label: t("持续运行", "Keep it moving"), description: t("把做过一次的工作变成定时或持续检查。", "Turn one completed task into scheduled or continuing work.") },
];

export const useCases: UseCase[] = [
  {
    id: "shape-a-task",
    category: "start",
    title: t("把脑中的一团事理成下一步", "Turn a messy thought into a next step"),
    summary: t("不必先写完整需求。把背景、顾虑和零散想法告诉 xopc，让它整理目标、边界和可执行的下一步。", "You do not need a polished brief. Give xopc the context, concerns, and fragments; it can shape the objective, boundaries, and next action."),
    prompt: t("我脑子里有一件还没想清楚的事：[描述现状]。先帮我区分事实、假设和待决定的问题，再整理成一个明确目标、完成标准和最小下一步。信息不足时一次问完。", "I have something I have not fully worked through: [describe the situation]. Separate facts, assumptions, and decisions, then turn it into a clear objective, completion criteria, and the smallest next step. Ask for missing information in one round."),
    outcome: t("一份明确的任务约定和下一步，不只是聊天总结。", "A clear task contract and next action, not just a chat summary."),
    setup: [],
    approval: t("只整理和建议，不会替你作关键决定。", "It organizes and recommends without making key decisions for you."),
    evidence: [t("目标与完成标准", "Objective and completion criteria"), t("下一步与阻塞项", "Next action and blockers")],
    productNodes: ["chat", "tasks", "home"],
  },
  {
    id: "resume-project",
    category: "start",
    title: t("接着上次的项目继续做", "Pick up a project where you left off"),
    summary: t("让 xopc 汇总项目中的任务、对话、笔记与最近结果，指出当前最值得推进的工作。", "Let xopc bring together tasks, conversations, notes, and recent results, then identify the most useful work to move next."),
    prompt: t("打开项目 [项目名]。根据已有任务、笔记和最近结果，告诉我现在处于什么状态、有哪些未决问题，以及今天最值得完成的一件事。确认后继续推进。", "Open project [project name]. Using its tasks, notes, and recent results, tell me where things stand, what remains unresolved, and the single most useful thing to finish today. Continue after I confirm."),
    outcome: t("跨会话保留的项目状态和明确的继续入口。", "Durable project state and a clear place to resume across sessions."),
    setup: [],
    approval: t("在改变项目方向前由你确认。", "You confirm before the project direction changes."),
    evidence: [t("项目状态摘要", "Project status summary"), t("最近结果与下一步", "Recent results and next action")],
    productNodes: ["projects", "memory", "tasks"],
  },
  {
    id: "voice-capture",
    category: "start",
    title: t("把一段语音变成可执行计划", "Turn a voice note into an actionable plan"),
    summary: t("口述想法或会议复盘，让 xopc 转写、提取决定与行动项，并放进任务或笔记。", "Speak an idea or meeting recap, then let xopc transcribe it, extract decisions and actions, and place them in tasks or notes."),
    prompt: t("转写这段语音，区分决定、行动项、问题和背景。把有明确负责人与截止时间的内容整理成任务，其余内容保存为笔记；先给我预览。", "Transcribe this recording and separate decisions, actions, questions, and context. Turn items with clear owners and deadlines into tasks, save the rest as a note, and show me a preview first."),
    outcome: t("从语音直接得到结构化笔记和待办事项。", "Structured notes and actionable work directly from speech."),
    setup: [t("配置语音识别模型", "Configure a speech-to-text model")],
    approval: t("创建或改动任务前先预览。", "Preview before tasks are created or changed."),
    evidence: [t("完整转写", "Full transcript"), t("行动项清单", "Action list")],
    productNodes: ["voice", "capture", "notes", "tasks"],
  },
  {
    id: "inbox-promises",
    category: "organize",
    title: t("找出邮件里答应过却没完成的事", "Find promises in your inbox that slipped"),
    summary: t("在你授权的 Gmail 范围内查找承诺、截止时间和未回复事项，并准备下一步。", "Search the Gmail scope you authorize for commitments, deadlines, and unanswered threads, then prepare the next step."),
    prompt: t("检查最近 [30] 天的邮件，找出我明确答应过但还没有完成或回复的事情。按影响和时效排序，为每一项写出证据、建议动作和回复草稿。不要发送。", "Review the last [30] days of email for things I explicitly promised but have not completed or answered. Rank them by impact and urgency, and provide evidence, a suggested action, and a reply draft for each. Do not send anything."),
    outcome: t("一份有邮件证据、可直接处理的承诺清单。", "An actionable commitment list backed by email evidence."),
    setup: [t("连接 Gmail", "Connect Gmail")],
    approval: t("发送邮件始终需要你的明确确认。", "Sending email always requires your explicit confirmation."),
    evidence: [t("来源邮件", "Source messages"), t("待发送草稿", "Draft replies")],
    productNodes: ["connectors", "tasks", "permissions"],
  },
  {
    id: "daily-plan",
    category: "organize",
    title: t("从日历和任务生成今日计划", "Build today's plan from calendar and tasks"),
    summary: t("合并已有会议、任务和时间边界，给出一份实际可执行的日程，而不是无限待办。", "Combine meetings, tasks, and time boundaries into a realistic day rather than an endless list."),
    prompt: t("查看我今天的日历和未完成任务。保留固定安排，按精力与截止时间安排最多三件重要工作，并标出缓冲时间和可能冲突。先给计划，不要改日历。", "Review today's calendar and open tasks. Keep fixed commitments, schedule no more than three important pieces of work around energy and deadlines, and flag buffers and conflicts. Show the plan without changing my calendar."),
    outcome: t("带冲突提示和优先级的现实日程。", "A realistic schedule with priorities and conflict warnings."),
    setup: [t("连接 Google Calendar", "Connect Google Calendar")],
    approval: t("写入或移动日历事件前确认。", "Confirm before creating or moving calendar events."),
    evidence: [t("引用的日历事件", "Referenced calendar events"), t("计划与冲突说明", "Plan and conflict notes")],
    productNodes: ["connectors", "home", "tasks"],
  },
  {
    id: "organize-files",
    category: "organize",
    title: t("整理一个混乱的本地文件夹", "Organize a messy local folder"),
    summary: t("读取指定工作区内的文件，识别重复、过期和未归档内容，先提出规则再执行。", "Inspect files inside an authorized workspace, identify duplicates and unfiled material, and propose rules before applying them."),
    prompt: t("分析文件夹 [路径]，按内容和日期提出一个简单的整理结构。列出重复文件、无法判断的文件和拟执行的移动/重命名操作。先给预览，我确认后再修改，并保留变更记录。", "Analyze folder [path] and propose a simple structure based on content and date. List duplicates, ambiguous files, and every proposed move or rename. Preview first, apply only after I confirm, and keep a change log."),
    outcome: t("可回顾的整理方案、变更记录和更清晰的文件结构。", "A reviewable organization plan, change log, and clearer folder structure."),
    setup: [t("授权指定工作区", "Authorize the intended workspace")],
    approval: t("移动、重命名或删除前确认。", "Confirm before moving, renaming, or deleting files."),
    evidence: [t("操作前预览", "Pre-change preview"), t("文件变更清单", "File change log")],
    productNodes: ["tools", "permissions", "notes"],
  },
  {
    id: "receipt-ledger",
    category: "organize",
    title: t("把收据整理成费用台账", "Turn receipts into an expense ledger"),
    summary: t("从图片或 PDF 提取商户、日期、金额和类别，标出无法确认的数据，并生成表格。", "Extract merchant, date, amount, and category from images or PDFs, flag uncertain fields, and produce a spreadsheet."),
    prompt: t("读取这些收据文件。提取日期、商户、金额、币种、税额和费用类别，保留原文件链接。对低置信度字段做标记，生成汇总表和异常清单，不要猜测缺失数字。", "Read these receipt files. Extract date, merchant, amount, currency, tax, and category while keeping links to the source files. Flag low-confidence fields, produce a summary table and an exceptions list, and do not invent missing numbers."),
    outcome: t("一份能核对来源的费用表和异常清单。", "A source-linked expense table and an exceptions list."),
    setup: [t("启用文件与表格能力", "Enable file and spreadsheet capabilities")],
    approval: t("只生成文件，不会自动报销或付款。", "It creates files without submitting reimbursements or payments."),
    evidence: [t("来源文件链接", "Source file links"), t("低置信度字段", "Low-confidence fields")],
    productNodes: ["media", "skills", "tools"],
  },
  {
    id: "compare-options",
    category: "research",
    title: t("带着约束比较产品或服务", "Compare products or services against your constraints"),
    summary: t("把预算、硬性条件和偏好交给 xopc，让它查找当前信息并解释取舍。", "Give xopc your budget, hard constraints, and preferences so it can find current information and explain the trade-offs."),
    prompt: t("帮我比较 [产品/服务]。预算是 [预算]，必须满足 [硬性条件]，偏好是 [偏好]。只使用当前可访问的可靠来源，给出候选、总成本、主要取舍和推荐，并附来源和查询日期。不要购买。", "Compare [product/service] for me. My budget is [budget], hard requirements are [requirements], and preferences are [preferences]. Use reliable current sources, show candidates, total cost, trade-offs, and a recommendation with source links and lookup dates. Do not purchase."),
    outcome: t("有来源、有约束、有取舍说明的推荐。", "A sourced recommendation grounded in constraints and trade-offs."),
    setup: [t("启用网页搜索", "Enable web search")],
    approval: t("购买或提交订单前必须由你确认。", "You must confirm before any purchase or order is submitted."),
    evidence: [t("来源链接与日期", "Source links and dates"), t("比较表", "Comparison table")],
    productNodes: ["tools", "browser", "permissions"],
  },
  {
    id: "source-brief",
    category: "research",
    title: t("做一份可追溯的研究简报", "Create a traceable research brief"),
    summary: t("围绕一个问题收集公开资料，区分事实、观点和未知，并把结论保存成笔记。", "Gather public material around a question, separate facts from opinions and unknowns, and save the conclusion as a note."),
    prompt: t("研究 [问题]，优先使用一手和权威来源。把确定事实、不同观点、仍未知的部分分开写，所有关键结论都附来源和发布日期。最后给我一页摘要，并保存为项目笔记。", "Research [question], prioritizing primary and authoritative sources. Separate established facts, competing views, and remaining unknowns; cite every important conclusion with its publication date. Finish with a one-page summary and save it as a project note."),
    outcome: t("一份能回到原始来源核验的简报。", "A brief whose conclusions can be checked against original sources."),
    setup: [t("启用网页搜索", "Enable web search")],
    approval: t("保存到项目前可先预览。", "Preview before saving it to a project."),
    evidence: [t("逐条来源", "Claim-level sources"), t("研究日期", "Research date")],
    productNodes: ["tools", "notes", "projects"],
  },
  {
    id: "account-admin",
    category: "research",
    title: t("在网站里完成一项账户事务", "Handle an account task in the browser"),
    summary: t("让 xopc 在已连接的浏览器中查找设置、准备表单或客服信息，并在真正提交前停下。", "Let xopc use a connected browser to find settings, prepare forms, or gather support information, then stop before the real submission."),
    prompt: t("在 [网站] 中处理 [账户事务]。先确认当前状态和可行路径，填写或准备所需内容，但在发送消息、取消服务、修改账户或付款前停下来让我确认。完成后给出页面状态和确认信息。", "Handle [account task] on [website]. First verify the current state and available path, prepare the required content, but pause before sending messages, canceling services, changing the account, or paying. When complete, report the final page state and confirmation information."),
    outcome: t("浏览器中的真实进展，同时保留最后决定权。", "Real browser progress while keeping the final decision with you."),
    setup: [t("连接浏览器并授权站点", "Connect a browser and authorize the site")],
    approval: t("外部写入、取消、购买和账户变更前确认。", "Confirm before external writes, cancellations, purchases, or account changes."),
    evidence: [t("操作前后状态", "Before-and-after state"), t("确认号或截图", "Confirmation number or screenshot")],
    productNodes: ["browser", "chrome", "permissions"],
  },
  {
    id: "draft-from-files",
    category: "create",
    title: t("从一组材料写出可交付初稿", "Draft a deliverable from source files"),
    summary: t("把本地文档、笔记和要求组合成结构化初稿，并明确哪些内容来自哪里。", "Combine local documents, notes, and requirements into a structured draft with clear source provenance."),
    prompt: t("根据这些材料起草一份 [报告/方案/说明]。先列出你将使用的来源和结构，再生成初稿。不要补造材料里没有的数字或结论；不确定的地方用待确认标记，并给出交付文件。", "Draft a [report/proposal/guide] from these materials. First list the sources and proposed structure, then create the draft. Do not invent numbers or conclusions not present in the source material; mark uncertainties for review and provide the deliverable file."),
    outcome: t("有来源边界、可继续编辑的交付文件。", "An editable deliverable with clear source boundaries."),
    setup: [t("授权源文件所在工作区", "Authorize the workspace containing the source files")],
    approval: t("发布或发送文件前确认。", "Confirm before publishing or sending the file."),
    evidence: [t("使用的来源清单", "Source list"), t("生成的文件", "Generated file")],
    productNodes: ["skills", "tools", "notes"],
  },
  {
    id: "image-variants",
    category: "create",
    title: t("生成并迭代一组视觉方案", "Generate and iterate on visual directions"),
    summary: t("描述用途、比例和视觉边界，先获得少量方向，再基于具体反馈继续修改。", "Describe the purpose, aspect ratio, and visual boundaries, get a small set of directions, then iterate with concrete feedback."),
    prompt: t("为 [用途] 生成视觉方案。目标受众是 [受众]，比例是 [比例]，必须包含 [元素]，避免 [元素/风格]。先提出三个清晰方向，选定后再生成并根据我的具体反馈迭代。", "Create visual directions for [purpose]. The audience is [audience], aspect ratio is [ratio], required elements are [elements], and avoid [elements/styles]. Propose three distinct directions first, then generate and iterate after I choose one."),
    outcome: t("经过方向确认和反馈迭代的图像文件。", "Image files refined through direction selection and feedback."),
    setup: [t("配置图像生成模型", "Configure an image generation model")],
    approval: t("每轮方向由你选择，不自动发布。", "You choose each direction; nothing is published automatically."),
    evidence: [t("生成文件", "Generated files"), t("采用的提示与修改记录", "Prompt and revision history")],
    productNodes: ["media", "skills", "projects"],
  },
  {
    id: "publish-local-app",
    category: "create",
    title: t("把一个想法做成本地小工具", "Turn an idea into a local tool"),
    summary: t("从目标和输入输出开始，让 xopc 构建一个在本机运行、可继续迭代的小应用。", "Start with the objective and inputs/outputs, then let xopc build a local app that can run on your machine and keep evolving."),
    prompt: t("为 [用户/场景] 做一个本地小工具，解决 [问题]。输入是 [输入]，需要输出 [输出]。先给最小版本和验收标准，再实现、运行检查并给我使用入口。未经确认不要部署到公网。", "Build a local tool for [user/scenario] that solves [problem]. Its input is [input] and output is [output]. Define the smallest version and acceptance criteria, implement it, verify it runs, and give me the local entry point. Do not deploy it publicly without confirmation."),
    outcome: t("一个能在本机打开并验证的应用，而不只是代码片段。", "A locally runnable, verified app rather than a code snippet."),
    setup: [t("启用编码与本地运行能力", "Enable coding and local runtime capabilities")],
    approval: t("公网发布、购买域名或外部部署前确认。", "Confirm before public deployment, domain purchases, or external hosting."),
    evidence: [t("运行结果", "Runtime result"), t("验收标准检查", "Acceptance checks")],
    productNodes: ["local-apps", "coding", "runtimes"],
  },
  {
    id: "implement-change",
    category: "build",
    title: t("在真实代码库中实现并验证改动", "Implement and verify a change in a real codebase"),
    summary: t("让 xopc 阅读本地仓库规则、定位相关代码、实施最小改动并运行验证。", "Let xopc read repository rules, locate the relevant code, implement the smallest change, and run verification."),
    prompt: t("在仓库 [路径] 实现：[需求]。先读取仓库说明和现有模式，说明会影响哪些区域，然后做最小改动。运行相关测试、类型检查或构建；保留用户已有改动，并报告文件、验证结果和剩余风险。", "In repository [path], implement: [requirement]. Read repository guidance and existing patterns first, explain the affected areas, then make the smallest change. Run relevant tests, type checks, or builds; preserve existing user changes and report files, verification, and remaining risks."),
    outcome: t("与仓库约定一致、经过验证的代码改动。", "A verified code change that follows the repository's conventions."),
    setup: [t("授权代码工作区与命令执行", "Authorize the code workspace and command execution")],
    approval: t("高风险命令、发布和外部写入前确认。", "Confirm before risky commands, releases, or external writes."),
    evidence: [t("代码差异", "Code diff"), t("测试或构建结果", "Test or build result")],
    productNodes: ["coding", "tools", "projects"],
  },
  {
    id: "review-change",
    category: "build",
    title: t("审查一次代码改动并指出真正风险", "Review a code change for real risks"),
    summary: t("结合仓库上下文检查正确性、回归、安全和测试缺口，避免只做表面风格评论。", "Use repository context to check correctness, regressions, security, and test gaps rather than offering surface-level style comments."),
    prompt: t("审查 [分支/PR/改动]。优先查找会导致错误结果、数据损坏、安全问题或兼容性回归的问题。每个发现给出文件位置、触发条件和修复建议；没有实质问题就明确说明。不要修改代码。", "Review [branch/PR/change]. Prioritize issues that can cause incorrect results, data loss, security problems, or compatibility regressions. For each finding, give the file location, trigger condition, and fix; say clearly if there are no material issues. Do not modify code."),
    outcome: t("按风险排序、可定位和复现的审查结论。", "Risk-ranked findings that are locatable and reproducible."),
    setup: [t("授权本地仓库，或连接 GitHub", "Authorize a local repository or connect GitHub")],
    approval: t("默认只读，不会评论、合并或推送。", "Read-only by default; it will not comment, merge, or push."),
    evidence: [t("精确文件位置", "Exact file locations"), t("验证方式", "Verification method")],
    productNodes: ["coding", "connectors", "permissions"],
  },
  {
    id: "morning-brief",
    category: "automate",
    title: t("每天生成一份带来源的行业简报", "Create a sourced industry brief every day"),
    summary: t("先手动跑通一次研究任务，再把同一套来源、范围和输出格式保存为自动化。", "Run the research task successfully once, then save the same sources, scope, and output format as an automation."),
    prompt: t("每天 [时间] 检查 [主题和来源范围]。只报告自上次运行以来的重要变化，附来源、发布时间和为什么值得关注。没有实质变化时保持安静；失败时通知我并保留可恢复状态。", "Every day at [time], check [topic and source scope]. Report only meaningful changes since the last run, including sources, publication time, and why each matters. Stay quiet when nothing material changed; notify me on failure and preserve a resumable state."),
    outcome: t("低噪音、可核验、失败可见的持续简报。", "A low-noise, verifiable brief with visible failures."),
    setup: [t("启用网页搜索与 Automation", "Enable web search and Automations")],
    approval: t("自动读取和生成结果；外部发送按渠道策略确认。", "Reading and result generation can run automatically; external sends follow channel policy."),
    evidence: [t("本次来源与变化", "Sources and changes for this run"), t("运行回执", "Run receipt")],
    productNodes: ["automations", "tools", "tasks"],
  },
  {
    id: "deadline-heartbeat",
    category: "automate",
    title: t("只在真正需要时提醒我", "Remind me only when attention is actually needed"),
    summary: t("让 Heartbeat 周期性查看任务或日程，但在状态没有实质变化时保持安静。", "Let Heartbeat periodically check tasks or calendar state while staying quiet when nothing meaningful has changed."),
    prompt: t("定期检查 [项目/任务范围]。只有在截止时间临近、任务阻塞、外部状态变化或确实需要我决定时提醒我。提醒中包含原因、证据和最小下一步；无变化时不要发状态消息。", "Periodically check [project/task scope]. Notify me only when a deadline is near, work is blocked, external state changes, or a real decision is needed. Include the reason, evidence, and smallest next step; send no status message when nothing changed."),
    outcome: t("安静但可靠的主动提醒，而不是周期性噪音。", "Quiet but reliable proactive attention instead of periodic noise."),
    setup: [t("配置 Heartbeat 范围和活跃时间", "Configure Heartbeat scope and active hours")],
    approval: t("提醒不会自动扩大已有执行权限。", "A reminder never expands existing execution authority."),
    evidence: [t("触发原因", "Trigger reason"), t("当前状态与下一步", "Current state and next step")],
    productNodes: ["heartbeat", "assistant", "home"],
  },
  {
    id: "repeat-browser-task",
    category: "automate",
    title: t("把跑通的网页操作保存为自动化", "Save a proven browser task as an automation"),
    summary: t("先在你的实际环境中完成并验证一次，再保存可复用步骤；网站变化时停止并报告。", "Complete and verify the task once in your environment, then save the reusable behavior; stop and report when the website changes."),
    prompt: t("把刚刚成功完成的 [网页任务] 保存为可复用自动化。沿用相同站点范围和审批点；每次运行核对关键页面状态，网站结构或结果不符合预期时停止，不要猜着点击，并报告已完成和剩余步骤。", "Save the [browser task] we just completed successfully as a reusable automation. Keep the same site scope and approval points; verify critical page state on every run, stop rather than guessing when the site or result differs, and report completed and remaining steps."),
    outcome: t("基于真实成功记录、能够检测漂移的网页自动化。", "Browser automation based on a real successful run with drift detection."),
    setup: [t("连接浏览器并先成功执行一次", "Connect a browser and complete one successful run first")],
    approval: t("沿用原任务的付款、发送和账户变更审批点。", "Keep the original approval points for payment, sending, and account changes."),
    evidence: [t("步骤完成计数", "Completed step count"), t("最终页面状态", "Final page state")],
    productNodes: ["browser-auto", "browser", "automations"],
  },
  {
    id: "continue-on-phone",
    category: "automate",
    title: t("离开电脑后继续同一件事", "Continue the same work away from your desk"),
    summary: t("通过移动端或消息渠道回到同一个 Runtime，继续查看任务、做决定和接收结果。", "Return to the same Runtime from mobile or a messaging channel to review tasks, make decisions, and receive results."),
    prompt: t("继续处理任务 [任务名]。先给我当前状态、刚完成的结果和现在需要我决定的唯一事项；不要重复已经完成的工作。", "Continue task [task name]. First show the current state, the latest completed result, and the single decision needed from me now; do not repeat work that is already complete."),
    outcome: t("跨设备延续同一任务，而不是开启一段失去上下文的新聊天。", "The same task continues across devices instead of becoming a new contextless chat."),
    setup: [t("连接移动端或消息渠道", "Connect the mobile app or a messaging channel")],
    approval: t("远程入口仍遵守原有权限与确认规则。", "Remote access keeps the original permission and confirmation rules."),
    evidence: [t("任务当前状态", "Current task state"), t("最近执行回执", "Latest execution receipt")],
    productNodes: ["mobile", "channels", "tasks"],
  },
];

export function localized(value: LocalizedText, locale: Locale): string {
  return value[locale];
}
